// Lista limpa e estruturada com objetos apontando para a pasta local img/
const PERSONAGENS = [
    { nome: "Alice | O Jaguadarte", img: "img/alice.png" },
    { nome: "Chapeuzinho Vermelho & O Caçador", img: "img/chapeuzinho.png" },
    { nome: "Sherlock Holmes | Dr. Watson", img: "img/sherlock.png" },
    { nome: "Drácula | As Três Irmãs", img: "img/dracula.png" },
    { nome: "Medusa | Harpias", img: "img/medusa.png" },
    { nome: "Robin Hood | Os Fora-da-lei", img: "img/robin_hood.png" },
    { nome: "Aquiles | Pátroclo", img: "img/aquiles.png" },
    { nome: "Beowulf & Wiglaf", img: "img/beowulf.png" },
    { nome: "Maria Sangrenta", img: "img/maria_sangrenta.png" },
    { nome: "O Gênio", img: "img/genio.png" },
    { nome: "Pé Grande | O Lebrílope", img: "img/pe_grande.png" },
    { nome: "Houdini | Bess", img: "img/houdini.png" },
    { nome: "Simbad | O Carregador", img: "img/simbad.png" },
    { nome: "Demolidor", img: "img/demolidor.png" },
    { nome: "Yennenga | Arqueiras", img: "img/yennenga.png" },
    { nome: "Dr. Jekyll | Sr. Hyde", img: "img/jekyll_hyde.png" },
    { nome: "Homem Invisível", img: "img/homem_invisivel.png" },
    { nome: "Annie Christmas | Charlie", img: "img/annie_christmas.png" },
    { nome: "Mercenário", img: "img/mercenario.png" },
    { nome: "Raptores", img: "img/raptores.png" },
    { nome: "Rei Arthur | Merlin", img: "img/rei_arthur.png" },
    { nome: "Robert Muldoon | Trabadores Ingen", img: "img/robert_muldoon.png" },
    { nome: "Shakespeare | Atores", img: "img/shakespeare.png" },
    { nome: "Sun Wukong", img: "img/sun_wukong.png" },
    { nome: "Tomoe Gozen", img: "img/tomoe_gozen.png" },
    { nome: "Eletrika | O tentáculo", img: "img/eletrika.png" },
    { nome: "Titânia | Oberon", img: "img/titania_oberon.png" },
    { nome: "As Irmãs Estranhas", img: "img/irmas_estranhas.png" },
    { nome: "Darth Vader", img: "img/darth_vader.png" },
    { nome: "Deadpool", img: "img/deadpool.png" },
    { nome: "Dra. Ellie Sattler | Dr. Ian Malcolm", img: "img/ellie_ian.png" },
    { nome: "Fantomas", img: "img/fantomas.png" },
    { nome: "Hamlet", img: "img/hamlet.png" },
    { nome: "Nicolas Tesla", img: "img/nicolas_tesla.png" },
    { nome: "Oda Nobunaga | Guarda de Honra", img: "img/oda_nobunaga.png" },
    { nome: "T-Rex", img: "img/t_rex.png" },
    { nome: "Homem-Mariposa | Sapo de Loveland", img: "img/homem_mariposa.png" },
    { nome: "Invasor maciano", img: "img/invasor_marciano.png" },
    { nome: "Jill Trent | Daizy", img: "img/jill_trent.png" },
    { nome: "Lampião e Corisco", img: "img/lampiao_corisco.png" }
];
